
import { Palette, Component, Network, Bot, TrendingUp, LifeBuoy, BookOpen, Brush, PenTool, Clapperboard, Server, Smartphone, Cloud, Link2, Database, GitMerge, BarChart, Search, MousePointerClick, Users, School, Zap, Cog, HelpCircle, ShieldCheck, DatabaseBackup, UserCheck, GraduationCap, Lightbulb, ShoppingCart, Store, Headset, Globe, FileText, Code, Brain, MessageSquare, Handshake, Briefcase, FileHeart, HeartHandshake } from "lucide-react";

export const serviceIcons: { [key: string]: React.ElementType } = {
  design: Palette,
  build: Component,
  integrate: Network,
  automate: Bot,
  grow: TrendingUp,
  support: LifeBuoy,
  learn: BookOpen,
  marketplace: Store,
  assist: Headset,
};

export const subServiceIcons: { [key: string]: React.ElementType } = {
    "UI/UX Design": Brush,
    "Branding & Identity": PenTool,
    "Creative & Motion": Clapperboard,
    "Product Design": FileText,
    "Design Systems": Code,
    "Web Development": Server,
    "Mobile App Development": Smartphone,
    "DevOps & Deployment": Cloud,
    "Quality Assurance": ShieldCheck,
    "AI Development": Brain,
    "ERP & Finance": Database,
    "POS & Inventory": GitMerge,
    "API & Middleware": Link2,
    "BI & Analytics": BarChart,
    "Healthcare Integration": FileHeart,
    "CRM & Workflow Automation": Zap,
    "AI Bots & Reporting": Bot,
    "Business Process Automation": Cog,
    "Marketing Automation": MessageSquare,
    "Sales Automation": TrendingUp,
    "SEO & GEO Optimization": Search,
    "Paid Media & Lead Gen": MousePointerClick,
    "Social & Content": Users,
    "Growth Workshops": School,
    "CRO": Handshake,
    "Helpdesk & SLAs": HelpCircle,
    "Cybersecurity & Compliance": ShieldCheck,
    "Maintenance & Lifecycle": DatabaseBackup,
    "Onboarding & Handover": UserCheck,
    "Managed Services": Briefcase,
    "Product Training": GraduationCap,
    "Marketing Bootcamps": Lightbulb,
    "E-commerce Skills": ShoppingCart,
    "Leadership & Strategy": Users,
    "Marketplace Management": Store,
    "E-commerce Platform Integration": ShoppingCart,
    "Compliance & Global Expansion": Globe,
    "Marketplace Analytics": BarChart,
    "Brand Store Management": Store,
    "Virtual Assistant Services": Headset,
    "Project Coordination": Briefcase,
    "Financial Administration": Database,
    "HR Support": Users,
    "Specialized Support": HeartHandshake,
};


export const baseCosts = {
  design: 1000,
  build: 3000,
  integrate: 2500,
  automate: 2000,
  grow: 1500,
  support: 600,
  learn: 400,
  marketplace: 800,
  assist: 250,
};

export const complexityLevels = [
  { id: 'simple', name: 'Simple', multiplier: 1 },
  { id: 'moderate', name: 'Moderate', multiplier: 1.5 },
  { id: 'complex', name: 'Complex', multiplier: 2.5 },
];

export const timelineUrgency = [
  { id: 'standard', name: 'Standard (Flexible)', multiplier: 1 },
  { id: 'expedited', name: 'Expedited (3-4 Weeks)', multiplier: 1.25 },
  { id: 'rush', name: 'Rush (1-2 Weeks)', multiplier: 1.5 },
];

export const dynamicQuestions: any = {
    'UI/UX Design': {
        'Product Design': [
            { id: 'user-research', name: 'User Research & Persona Development', type: 'checkbox', cost: 500, description: 'Conduct user interviews and surveys to create detailed user personas.' },
            { id: 'user-journey', name: 'User Journey Mapping', type: 'checkbox', cost: 300, description: 'Visualize the end-to-end experience a user has with your product.' },
            { id: 'wireframing', name: 'Wireframing (up to 10 screens)', type: 'checkbox', cost: 600, description: 'Create low-fidelity blueprints to outline the structure and layout.' },
            { id: 'high-fidelity', name: 'High-Fidelity Mockups (up to 10 screens)', type: 'checkbox', cost: 800, description: 'Develop detailed, pixel-perfect visual designs of the user interface.' },
            { id: 'interactive-prototype', name: 'Interactive Prototype (Figma)', type: 'checkbox', cost: 700, description: 'Build a clickable prototype to simulate user interactions and workflows.' },
            { id: 'design-system', name: 'Basic Design System', type: 'checkbox', cost: 1000, description: 'Create a library of reusable UI components and guidelines for consistency.' },
            { id: 'accessibility-audit', name: 'Accessibility Audit (WCAG)', type: 'checkbox', cost: 400, description: 'Ensure the product is usable by people with disabilities.' },
            { id: 'usability-testing', name: 'Usability Testing (5 users)', type: 'checkbox', cost: 600, description: 'Observe real users interacting with the product to identify issues.' },
            { id: 'design-handoff', name: 'Developer Handoff Documentation', type: 'checkbox', cost: 250, description: 'Prepare and organize all design assets and specifications for development.' },
            { id: 'design-workshop', name: 'Collaborative Design Workshop', type: 'checkbox', cost: 350, description: 'Facilitate a workshop with stakeholders to align on design goals.' },
        ],
        'Website/App Redesign': [
            { id: 'design-audit', name: 'Current UX/UI Audit', type: 'checkbox', cost: 500, description: 'Evaluate the existing design to identify strengths and weaknesses.' },
            { id: 'competitor-analysis', name: 'Competitor UI/UX Analysis', type: 'checkbox', cost: 350, description: 'Analyze competitor products to find opportunities for improvement.' },
            { id: 'information-architecture', name: 'Information Architecture Redesign', type: 'checkbox', cost: 600, description: 'Restructure and organize content for better usability and navigation.' },
            { id: 'visual-redesign', name: 'Visual Redesign (up to 10 screens)', type: 'checkbox', cost: 900, description: 'Update the visual appearance to be modern and on-brand.' },
            { id: 'prototype-redesign', name: 'Interactive Prototype of New Design', type: 'checkbox', cost: 700, description: 'Create a clickable prototype of the redesigned interface.' },
            { id: 'user-feedback', name: 'User Feedback Collection on Existing Design', type: 'checkbox', cost: 400, description: 'Gather insights from current users to inform the redesign.' },
            { id: 'mobile-optimization', name: 'Mobile Responsiveness Redesign', type: 'checkbox', cost: 500, description: 'Ensure the design is optimized for a seamless mobile experience.' },
            { id: 'style-guide-update', name: 'Update/Create Style Guide', type: 'checkbox', cost: 650, description: 'Develop or update a comprehensive guide for visual consistency.' },
            { id: 'a-b-testing', name: 'A/B Testing Setup for New Designs', type: 'checkbox', cost: 450, description: 'Set up tests to compare different design variations and measure impact.' },
            { id: 'performance-review', name: 'Post-Redesign Performance Review', type: 'checkbox', cost: 350, description: 'Analyze metrics after launch to measure the success of the redesign.' },
        ]
    },
    'Branding & Identity': {
        'Brand Foundation': [
            { 
                id: 'logo-design', name: 'Logo Design (3 Concepts)', type: 'checkbox', cost: 400, description: 'Develop three unique logo concepts for your brand.',
                subFeatures: [
                     { id: 'logo-extra-concept', name: 'Additional Concept', type: 'checkbox', cost: 120, description: 'Get one more unique logo concept to choose from.' },
                     { id: 'logo-social-kit', name: 'Social Media Kit', type: 'checkbox', cost: 180, description: 'Profile and cover images for your social media channels.' },
                     { id: 'logo-animated', name: 'Animated Logo', type: 'checkbox', cost: 250, description: 'A short, animated version of your logo for video content.' },
                ]
            },
            { id: 'brand-discovery', name: 'Brand Discovery Workshop', type: 'checkbox', cost: 300, description: 'A collaborative session to define your brand’s core values and personality.' },
            { id: 'color-palette', name: 'Color Palette Development', type: 'checkbox', cost: 150, description: 'Define a primary and secondary color palette that reflects your brand.' },
            { id: 'typography-system', name: 'Typography System', type: 'checkbox', cost: 150, description: 'Select and pair fonts for headings, body text, and other uses.' },
            { id: 'brand-voice', name: 'Brand Voice & Tone Guidelines', type: 'checkbox', cost: 250, description: 'Establish guidelines for how your brand communicates in writing.' },
            { id: 'mission-vision', name: 'Mission & Vision Statements', type: 'checkbox', cost: 200, description: 'Craft powerful statements that define your brand’s purpose.' },
            { id: 'competitor-analysis-brand', name: 'Competitor Brand Analysis', type: 'checkbox', cost: 280, description: 'Analyze competitor branding to identify differentiation opportunities.' },
            { id: 'target-audience', name: 'Target Audience Persona', type: 'checkbox', cost: 200, description: 'Create a detailed profile of your ideal customer.' },
            { id: 'style-guide-mini', name: 'Mini Style Guide (10 pages)', type: 'checkbox', cost: 500, description: 'A concise document outlining the essential rules for your brand identity.' },
            { 
                id: 'style-guide-full', name: 'Full Brand Style Guide (20+ pages)', type: 'checkbox', cost: 1000, description: 'A comprehensive document covering all aspects of your brand identity.',
                subFeatures: [
                    { id: 'style-guide-print', name: 'Print & Production Guidelines', type: 'checkbox', cost: 280, description: 'Guidelines for using your brand on physical materials.' },
                    { id: 'style-guide-digital', name: 'Digital Usage Guidelines', type: 'checkbox', cost: 200, description: 'Rules for applying your brand across digital platforms.' },
                ]
            },
        ],
        'Marketing Assets': [
            { id: 'business-cards', name: 'Business Card Design', type: 'checkbox', cost: 80, description: 'A professional business card design that represents your brand.' },
            { id: 'letterhead', name: 'Letterhead & Envelope Design', type: 'checkbox', cost: 100, description: 'Branded design for your official company stationery.' },
            { id: 'social-media-templates', name: 'Social Media Templates (5 templates)', type: 'checkbox', cost: 300, description: 'Editable templates for posts on platforms like Instagram and Facebook.' },
            { id: 'presentation-template', name: 'Presentation Template (PowerPoint/Google Slides)', type: 'checkbox', cost: 320, description: 'A branded template for your company presentations.' },
            { id: 'brochure-design', name: 'Brochure/Flyer Design', type: 'checkbox', cost: 250, description: 'A professional design for a tri-fold brochure or single-page flyer.' },
            { id: 'email-signature', name: 'Email Signature Design', type: 'checkbox', cost: 60, description: 'A branded email signature for all company employees.' },
            { id: 'ad-creatives', name: 'Digital Ad Creatives (Set of 3 sizes)', type: 'checkbox', cost: 200, description: 'A set of branded graphics for online advertising campaigns.' },
            { id: 'packaging-design', name: 'Product Packaging Design', type: 'checkbox', cost: 600, description: 'Creative and practical design for your product’s packaging.' },
            { id: 'tshirt-design', name: 'T-Shirt/Merchandise Design', type: 'checkbox', cost: 160, description: 'A cool design for branded t-shirts or other merchandise.' },
            { id: 'trade-show-booth', name: 'Trade Show Booth Graphics', type: 'checkbox', cost: 800, description: 'Eye-catching graphics for your booth at a trade show or event.' },
        ]
    },
    'Creative & Motion': {
        'Video Production': [
            { id: 'explainer-video', name: 'Animated Explainer Video (60s)', type: 'checkbox', cost: 1200, description: 'A 60-second animated video explaining your product or service.' },
            { id: 'social-video-ads', name: 'Social Media Video Ads (3 ads)', type: 'checkbox', cost: 600, description: 'A set of three short, engaging video ads for social media.' },
            { id: 'product-demo-video', name: 'Product Demo Video', type: 'checkbox', cost: 800, description: 'A video showcasing the features and benefits of your product.' },
            { id: 'corporate-video', name: 'Corporate Brand Video', type: 'checkbox', cost: 1600, description: 'A high-quality video that tells your company’s story and values.' },
            { id: 'ui-animation', name: 'UI/App Motion Graphics', type: 'checkbox', cost: 720, description: 'Subtle animations to enhance the user experience of your app.' },
            { id: 'logo-animation', name: 'Logo Animation', type: 'checkbox', cost: 250, description: 'Bring your logo to life with a short, professional animation.' },
            { id: 'scriptwriting', name: 'Scriptwriting Service', type: 'checkbox', cost: 320, description: 'Professional scriptwriting for your video content.' },
            { id: 'storyboarding', name: 'Storyboarding', type: 'checkbox', cost: 280, description: 'Visual planning of your video, shot by shot.' },
            { id: 'voiceover', name: 'Professional Voiceover', type: 'checkbox', cost: 200, description: 'A professional voiceover recording for your video.' },
            { id: 'subtitling', name: 'Subtitling and Captions', type: 'checkbox', cost: 120, description: 'Add subtitles or captions to your video for accessibility.' },
        ],
        'Visual Content': [
            { id: 'infographics', name: 'Infographic Design (2)', type: 'checkbox', cost: 400, description: 'Two custom infographics to visually represent data or information.' },
            { id: '3d-mockups', name: '3D Product Mockups (5)', type: 'checkbox', cost: 600, description: 'Five realistic 3D mockups of your product.' },
            { id: 'iconography-set', name: 'Custom Iconography Set (20 icons)', type: 'checkbox', cost: 500, description: 'A set of 20 custom-designed icons for your website or app.' },
            { id: 'presentation-design', name: 'Custom Presentation Design (20 slides)', type: 'checkbox', cost: 720, description: 'A custom-designed 20-slide presentation deck.' },
            { id: 'ebook-design', name: 'eBook/Whitepaper Design', type: 'checkbox', cost: 520, description: 'Professional layout and design for your eBook or whitepaper.' },
            { id: 'social-media-content', name: 'Social Media Static Posts (10)', type: 'checkbox', cost: 360, description: 'Ten custom-designed static posts for your social media channels.' },
            { id: 'ad-creative-design', name: 'Digital Ad Creatives (5 variations)', type: 'checkbox', cost: 450, description: 'Five variations of ad creatives for A/B testing.' },
            { id: 'photo-retouching', name: 'Professional Photo Retouching (10 images)', type: 'checkbox', cost: 280, description: 'Professional retouching for up to 10 photos.' },
            { id: 'custom-illustrations', name: 'Custom Illustrations (5)', type: 'checkbox', cost: 650, description: 'Five unique, custom illustrations in your brand’s style.' },
            { id: 'art-direction', name: 'Art Direction for Photoshoot', type: 'checkbox', cost: 800, description: 'Creative direction and planning for a professional photoshoot.' },
        ]
    },
    'Web Development': {
        'E-commerce': [
            { id: 'shopify-setup', name: 'Shopify Store Setup', type: 'checkbox', cost: 600, description: 'Basic setup and configuration of a new Shopify store.' },
            { id: 'woocommerce-setup', name: 'WooCommerce Store Setup', type: 'checkbox', cost: 720, description: 'Setup and configuration of WooCommerce on your WordPress site.' },
            { id: 'custom-theme', name: 'Custom Theme Development', type: 'checkbox', cost: 1600, description: 'A bespoke theme for Shopify or WooCommerce, designed from scratch.' },
            { id: 'payment-integration', name: 'Payment Gateway Integration (Stripe/Local)', type: 'checkbox', cost: 320, description: 'Integration of a payment gateway like Stripe or a local provider.' },
            { id: 'product-upload', name: 'Product Data Entry (up to 100 products)', type: 'checkbox', cost: 250, description: 'Manual entry of up to 100 products into your e-commerce platform.' },
            { id: 'subscription-model', name: 'Subscription/Recurring Payments Setup', type: 'checkbox', cost: 500, description: 'Set up a subscription service with recurring payments.' },
            { id: 'custom-plugin', name: 'Custom Plugin/App Development', type: 'checkbox', cost: 1000, description: 'Development of a custom plugin or app to extend functionality.' },
            { id: 'shipping-logic', name: 'Advanced Shipping Logic', type: 'checkbox', cost: 360, description: 'Implementation of complex shipping rules and calculations.' },
            { id: 'inventory-sync', name: 'Inventory Management Integration', type: 'checkbox', cost: 520, description: 'Integration with an external inventory management system.' },
            { id: 'seo-ecommerce', name: 'E-commerce SEO Setup', type: 'checkbox', cost: 400, description: 'Basic SEO setup for product pages, collections, and the homepage.' },
        ],
        'Web Application': [
            { id: 'auth', name: 'User Authentication (Email/Social)', type: 'checkbox', cost: 600, description: 'Allow users to sign up and log in with email or social accounts.' },
            { id: 'dashboard', name: 'User Dashboard', type: 'checkbox', cost: 800, description: 'A personalized dashboard for logged-in users.' },
            { id: 'database', name: 'Database Setup (Firebase/Postgres)', type: 'checkbox', cost: 500, description: 'Setup and configuration of a new database.' },
            { id: 'api-dev', name: 'Custom Backend API (Node.js/Express)', type: 'checkbox', cost: 1400, description: 'Development of a custom API to power your application.' },
            { id: 'admin-panel', name: 'Admin Panel/CMS', type: 'checkbox', cost: 1000, description: 'A dashboard for administrators to manage the application.' },
            { id: 'real-time', name: 'Real-time features (WebSockets)', type: 'checkbox', cost: 720, description: 'Implementation of real-time features like chat or notifications.' },
            { id: 'third-party-api', name: 'Third-party API Integration', type: 'checkbox', cost: 400, description: 'Integration with an external API to pull or push data.' },
            { id: 'search-feature', name: 'Advanced Search Functionality', type: 'checkbox', cost: 520, description: 'Implementation of a powerful and fast search feature.' },
            { id: 'file-uploads', name: 'File Uploads & Storage', type: 'checkbox', cost: 360, description: 'Allow users to upload files, and store them securely.' },
            { id: 'unit-testing', name: 'Unit & Integration Testing', type: 'checkbox', cost: 650, description: 'Writing automated tests to ensure code quality and reliability.' },
        ],
        'Marketing Website': [
            { id: 'multi-page', name: 'Up to 10 pages', type: 'checkbox', cost: 800, description: 'Development of a website with up to 10 static pages.' },
            { id: 'cms-integration', name: 'Headless CMS Integration (Sanity/Strapi)', type: 'checkbox', cost: 600, description: 'Integration with a headless CMS for easy content management.' },
            { id: 'blog', name: 'Blog Setup and Design', type: 'checkbox', cost: 320, description: 'Setup and design of a blog section on your website.' },
            { id: 'analytics-setup', name: 'Google Analytics & Tag Manager Setup', type: 'checkbox', cost: 200, description: 'Proper setup of Google Analytics and Tag Manager for tracking.' },
            { id: 'contact-form', name: 'Contact/Lead Form with Email Notifications', type: 'checkbox', cost: 160, description: 'A contact form that sends submissions to your email.' },
            { id: 'newsletter-signup', name: 'Newsletter Signup Integration (Mailchimp)', type: 'checkbox', cost: 160, description: 'Integration with Mailchimp or another email marketing service.' },
            { id: 'multi-language', name: 'Multi-language Support', type: 'checkbox', cost: 500, description: 'Implementation of support for multiple languages.' },
            { id: 'on-page-seo', name: 'On-Page SEO Optimization', type: 'checkbox', cost: 360, description: 'Optimization of titles, meta descriptions, and content for SEO.' },
            { id: 'animations', name: 'On-scroll Animations & Micro-interactions', type: 'checkbox', cost: 400, description: 'Subtle animations to enhance the user experience.' },
            { id: 'hosting-setup-web', name: 'Hosting Setup (Vercel/Netlify)', type: 'checkbox', cost: 120, description: 'Setup and configuration of hosting on Vercel or Netlify.' },
        ]
    },
    'Mobile App Development': {
        'Native App': [
            { id: 'ios-swift', name: 'iOS App (Swift)', type: 'checkbox', cost: 5000, description: 'Development of a native iOS app using Swift.' },
            { id: 'android-kotlin', name: 'Android App (Kotlin)', type: 'checkbox', cost: 5000, description: 'Development of a native Android app using Kotlin.' },
            { id: 'firebase-backend', name: 'Firebase Backend Setup', type: 'checkbox', cost: 600, description: 'Setup of a Firebase project to serve as the backend.' },
            { id: 'push-notifications', name: 'Push Notifications', type: 'checkbox', cost: 320, description: 'Implementation of push notifications to engage users.' },
            { id: 'in-app-purchases', name: 'In-App Purchases/Subscriptions', type: 'checkbox', cost: 600, description: 'Allow users to make purchases or subscribe within the app.' },
            { id: 'offline-mode', name: 'Offline Mode/Sync', type: 'checkbox', cost: 800, description: 'Allow the app to function without an internet connection.' },
            { id: 'maps-location', name: 'Maps & Geolocation Features', type: 'checkbox', cost: 720, description: 'Integration of maps and location-based features.' },
            { id: 'camera-media', name: 'Camera & Media Integration', type: 'checkbox', cost: 520, description: 'Allow users to take photos or select media from their device.' },
            { id: 'app-store-submission', name: 'App Store Submission & Review', type: 'checkbox', cost: 400, description: 'Preparation and submission of the app to the app stores.' },
            { id: 'analytics-mobile', name: 'Mobile Analytics Integration', type: 'checkbox', cost: 280, description: 'Integration of an analytics service to track app usage.' },
        ],
        'Cross-Platform App': [
            { id: 'react-native-app', name: 'React Native App (iOS & Android)', type: 'checkbox', cost: 7000, description: 'Development of a cross-platform app using React Native.' },
            { id: 'custom-backend-mobile', name: 'Custom Backend API for Mobile', type: 'checkbox', cost: 2000, description: 'Development of a custom API to power your mobile app.' },
            { id: 'social-login-mobile', name: 'Social Logins (Google/Facebook/Apple)', type: 'checkbox', cost: 500, description: 'Allow users to log in with their social media accounts.' },
            { id: 'pwa', name: 'Progressive Web App (PWA) Version', type: 'checkbox', cost: 1200, description: 'Development of a PWA for a web-based mobile experience.' },
            { id: 'biometric-auth', name: 'Biometric Authentication (Face/Touch ID)', type: 'checkbox', cost: 400, description: 'Allow users to log in using biometric authentication.' },
            { id: 'bluetooth-integration', name: 'Bluetooth/NFC Integration', type: 'checkbox', cost: 1000, description: 'Integration with Bluetooth or NFC for device communication.' },
            { id: 'chat-feature', name: 'In-App Chat/Messaging', type: 'checkbox', cost: 900, description: 'Implementation of a real-time chat feature within the app.' },
            { id: 'payment-sdk', name: 'Payment SDK Integration', type: 'checkbox', cost: 560, description: 'Integration of a payment SDK for in-app transactions.' },
            { id: 'code-sharing', name: 'Code Sharing Strategy for Web & Mobile', type: 'checkbox', cost: 720, description: 'A strategy to share code between your web and mobile apps.' },
            { id: 'maintenance-plan', name: '6-Month Maintenance & Support Plan', type: 'checkbox', cost: 1200, description: 'A plan to provide ongoing maintenance and support for 6 months.' },
        ]
    },
    'DevOps & Deployment': {
        'CI/CD & Automation': [
            { id: 'github-actions', name: 'CI/CD Pipeline Setup (GitHub Actions)', type: 'checkbox', cost: 600, description: 'Automate your build, test, and deployment process with GitHub Actions.' },
            { id: 'automated-testing', name: 'Automated Testing Pipeline (Unit, E2E)', type: 'checkbox', cost: 800, description: 'Set up a pipeline to run automated tests on every code change.' },
            { id: 'dockerization', name: 'Application Containerization (Docker)', type: 'checkbox', cost: 500, description: 'Package your application into a Docker container for portability.' },
            { id: 'iac', name: 'Infrastructure as Code (Terraform/CloudFormation)', type: 'checkbox', cost: 1000, description: 'Manage your cloud infrastructure using code for consistency.' },
            { id: 'blue-green', name: 'Blue/Green Deployment Strategy', type: 'checkbox', cost: 720, description: 'Implement a deployment strategy that minimizes downtime and risk.' },
            { id: 'secret-management', name: 'Secret Management (Vault/AWS KMS)', type: 'checkbox', cost: 360, description: 'Securely manage and access your application’s secrets.' },
            { id: 'code-quality', name: 'Automated Code Quality & Security Scans', type: 'checkbox', cost: 450, description: 'Automatically scan your code for quality issues and security vulnerabilities.' },
            { id: 'artifact-repo', name: 'Artifact Repository Setup (Docker Hub/ECR)', type: 'checkbox', cost: 320, description: 'Set up a repository to store and manage your application’s artifacts.' },
            { id: 'deployment-notifications', name: 'Deployment Notifications (Slack/Email)', type: 'checkbox', cost: 200, description: 'Get notified in Slack or by email when deployments happen.' },
            { id: 'pipeline-dashboard', name: 'CI/CD Pipeline Monitoring Dashboard', type: 'checkbox', cost: 520, description: 'A dashboard to visualize the status and history of your pipelines.' },
        ],
        'Cloud Infrastructure': [
            { id: 'aws-setup', name: 'AWS Account Setup & Best Practices', type: 'checkbox', cost: 400, description: 'Set up your AWS account following security and operational best practices.' },
            { id: 'gcp-setup', name: 'Google Cloud Platform Setup & Best Practices', type: 'checkbox', cost: 400, description: 'Set up your GCP account following security and operational best practices.' },
            { id: 'serverless-arch', name: 'Serverless Architecture Setup (Lambda/Cloud Functions)', type: 'checkbox', cost: 900, description: 'Design and set up a serverless architecture for your application.' },
            { id: 'kubernetes-setup', name: 'Kubernetes Cluster Setup (EKS/GKE)', type: 'checkbox', cost: 1600, description: 'Set up and configure a Kubernetes cluster to run your application.' },
            { id: 'vpc-setup', name: 'VPC and Network Configuration', type: 'checkbox', cost: 600, description: 'Configure a Virtual Private Cloud (VPC) to isolate your resources.' },
            { id: 'monitoring-logging', name: 'Monitoring, Logging, and Alerting Setup', type: 'checkbox', cost: 720, description: 'Set up tools to monitor your application, collect logs, and send alerts.' },
            { id: 'cost-optimization', name: 'Cloud Cost Optimization Audit', type: 'checkbox', cost: 500, description: 'Analyze your cloud usage and provide recommendations to reduce costs.' },
            { id: 'backup-dr', name: 'Backup and Disaster Recovery Strategy', type: 'checkbox', cost: 650, description: 'Develop a strategy to back up your data and recover from disasters.' },
            { id: 'cdn-setup', name: 'CDN Setup (Cloudflare/CloudFront)', type: 'checkbox', cost: 320, description: 'Set up a Content Delivery Network (CDN) to improve performance.' },
            { id: 'database-managed', name: 'Managed Database Setup (RDS/Cloud SQL)', type: 'checkbox', cost: 560, description: 'Set up a managed database service for reliability and scalability.' },
        ]
    },
    'ERP & Finance': {
        'Odoo Integration': [
            { id: 'odoo-crm', name: 'Odoo CRM & Sales Integration', type: 'checkbox', cost: 1000, description: 'Integrate your sales process with Odoo CRM for a unified view.' },
            { id: 'odoo-inventory', name: 'Odoo Inventory Management Integration', type: 'checkbox', cost: 1200, description: 'Sync your inventory data with Odoo for accurate tracking.' },
            { id: 'odoo-accounting', name: 'Odoo Accounting Integration', type: 'checkbox', cost: 1100, description: 'Automate your accounting process by integrating with Odoo.' },
            { id: 'odoo-ecommerce', name: 'Odoo E-commerce (Website) Integration', type: 'checkbox', cost: 1400, description: 'Connect your e-commerce store with Odoo for seamless operations.' },
            { id: 'custom-odoo-module', name: 'Custom Odoo Module Development', type: 'checkbox', cost: 1600, description: 'Develop a custom Odoo module to meet your specific needs.' },
            { id: 'data-migration-odoo', name: 'Data Migration to Odoo', type: 'checkbox', cost: 800, description: 'Migrate your existing data from another system to Odoo.' },
            { id: 'odoo-reporting', name: 'Custom Reporting & Dashboards in Odoo', type: 'checkbox', cost: 720, description: 'Create custom reports and dashboards within Odoo for insights.' },
            { id: 'odoo-workflow', name: 'Workflow Automation within Odoo', type: 'checkbox', cost: 600, description: 'Automate your business processes and workflows within Odoo.' },
            { id: 'odoo-training', name: 'Odoo User Training', type: 'checkbox', cost: 500, description: 'Provide training to your team on how to use Odoo effectively.' },
            { id: 'odoo-support', name: 'Odoo Maintenance & Support Retainer', type: 'checkbox', cost: 400, description: 'Get ongoing maintenance and support for your Odoo instance.' },
        ],
        'Financial Systems': [
            { id: 'quickbooks-integration', name: 'QuickBooks Integration with Sales Channels', type: 'checkbox', cost: 720, description: 'Sync your sales data with QuickBooks for easy accounting.' },
            { id: 'xero-integration', name: 'Xero Integration with Sales Channels', type: 'checkbox', cost: 720, description: 'Sync your sales data with Xero for streamlined bookkeeping.' },
            { id: 'automated-invoicing', name: 'Automated Invoicing System', type: 'checkbox', cost: 600, description: 'Automatically generate and send invoices to your customers.' },
            { id: 'expense-tracking', name: 'Expense Tracking Automation', type: 'checkbox', cost: 520, description: 'Automate the process of tracking and categorizing business expenses.' },
            { id: 'payroll-integration', name: 'Payroll System Integration', type: 'checkbox', cost: 650, description: 'Integrate your payroll system for seamless salary processing.' },
            { id: 'payment-reconciliation', name: 'Automated Payment Reconciliation', type: 'checkbox', cost: 800, description: 'Automatically reconcile payments from various channels.' },
            { id: 'financial-dashboard', name: 'Consolidated Financial Dashboard', type: 'checkbox', cost: 900, description: 'A single dashboard to view all your key financial metrics.' },
            { id: 'tax-calculation', name: 'Automated Tax Calculation Integration', description: 'Automatically calculate taxes on your sales transactions.', cost: 560, type: 'checkbox' },
            { id: 'multi-currency', name: 'Multi-currency Handling & Reporting', description: 'Support for multiple currencies in your financial transactions.', cost: 680, type: 'checkbox' },
            { id: 'legacy-fin-system', name: 'Integration with Legacy Financial System', type: 'checkbox', cost: 1400, description: 'Integrate with an older, legacy financial system.' },
        ]
    },
    'POS & Inventory': {
        'Omnichannel Retail': [
            { id: 'pos-ecommerce-sync', name: 'POS & E-commerce Real-time Sync', type: 'checkbox', cost: 1200, description: 'Real-time synchronization between your POS and e-commerce store.' },
            { id: 'multi-location-inventory', name: 'Multi-location Inventory Management', type: 'checkbox', cost: 1000, description: 'Manage inventory across multiple physical and online locations.' },
            { id: 'click-collect', name: 'Click-and-Collect / BOPIS Setup', type: 'checkbox', cost: 720, description: 'Allow customers to buy online and pick up in-store.' },
            { id: 'unified-customer-profiles', name: 'Unified Customer Profiles (Online & In-store)', type: 'checkbox', cost: 900, description: 'Create a single view of your customers across all channels.' },
            { id: 'cross-channel-promotions', name: 'Cross-channel Promotions & Discounts Engine', type: 'checkbox', cost: 650, description: 'Run promotions that work seamlessly online and in-store.' },
            { id: 'loyalty-program', name: 'Unified Loyalty Program Integration', type: 'checkbox', cost: 800, description: 'Integrate a loyalty program that rewards customers everywhere.' },
            { id: 'barcode-rfid', name: 'Barcode/RFID System Integration', type: 'checkbox', cost: 600, description: 'Integrate with barcode scanners or RFID systems for inventory.' },
            { id: 'returns-management', name: 'Centralized Returns Management System', type: 'checkbox', cost: 680, description: 'A system to manage returns from both online and in-store purchases.' },
            { id: 'supplier-integration', name: 'Supplier/Dropshipper Integration', type: 'checkbox', cost: 1100, description: 'Integrate with your suppliers or dropshippers for automated ordering.' },
            { id: 'aster-pos', name: 'ASTER POS Integration', type: 'checkbox', cost: 800, description: 'Specific integration with the ASTER Point-of-Sale system.' },
        ]
    },
    'API & Middleware': {
        'Custom API Development': [
            { id: 'rest-api', name: 'Custom REST API Development', type: 'checkbox', cost: 1400, description: 'Develop a custom REST API to expose your data and functionality.' },
            { id: 'graphql-api', name: 'Custom GraphQL API Development', type: 'checkbox', cost: 1600, description: 'Develop a custom GraphQL API for flexible data fetching.' },
            { id: 'api-documentation', name: 'Interactive API Documentation (Swagger/OpenAPI)', type: 'checkbox', cost: 400, description: 'Create interactive and easy-to-use documentation for your API.' },
            { id: 'api-auth', name: 'API Authentication (OAuth 2.0/JWT)', type: 'checkbox', cost: 500, description: 'Secure your API with standard authentication mechanisms.' },
            { id: 'api-testing', name: 'API Automated Testing Suite', type: 'checkbox', cost: 600, description: 'Write automated tests to ensure the reliability of your API.' },
            { id: 'api-versioning', name: 'API Versioning Strategy', type: 'checkbox', cost: 320, description: 'Implement a strategy for versioning your API to avoid breaking changes.' },
            { id: 'api-rate-limiting', name: 'Rate Limiting and Throttling', type: 'checkbox', cost: 360, description: 'Protect your API from abuse with rate limiting and throttling.' },
            { id: 'webhook-dev', name: 'Webhook Development and Management', type: 'checkbox', cost: 520, description: 'Develop webhooks to notify other systems of events.' },
            { id: 'api-monitoring', name: 'API Performance and Usage Monitoring', type: 'checkbox', cost: 450, description: 'Monitor the performance and usage of your API.' },
            { id: 'api-gateway', name: 'API Gateway Setup (e.g., AWS API Gateway)', type: 'checkbox', cost: 720, description: 'Set up an API gateway to manage and secure your APIs.' },
        ],
        'iPaaS & ETL': [
            { id: 'make-workflow', name: 'Complex Workflow Automation on Make.com', type: 'checkbox', cost: 800, description: 'Design and implement complex automation scenarios using Make.com.' },
            { id: 'zapier-workflow', name: 'Complex Workflow Automation on Zapier', type: 'checkbox', cost: 800, description: 'Design and implement complex automation scenarios using Zapier.' },
            { id: 'etl-pipeline', name: 'ETL Pipeline Development', type: 'checkbox', cost: 1200, description: 'Develop pipelines to Extract, Transform, and Load data between systems.' },
            { id: 'data-warehouse-integration', name: 'Integration with Data Warehouse (BigQuery/Snowflake)', type: 'checkbox', cost: 1000, description: 'Connect your data sources to a central data warehouse.' },
            { id: 'data-transformation', name: 'Custom Data Transformation Logic', type: 'checkbox', cost: 600, description: 'Write custom scripts to transform data as it moves between systems.' },
            { id: 'third-party-connector', name: 'Integration with 5+ Third-Party Apps', type: 'checkbox', cost: 900, description: 'Connect more than five different third-party applications.' },
            { id: 'real-time-data-stream', name: 'Real-time Data Streaming Setup (e.g., Kafka)', type: 'checkbox', cost: 1400, description: 'Set up a real-time data streaming platform for instant data flow.' },
            { id: 'error-handling-retry', name: 'Advanced Error Handling and Retry Logic', type: 'checkbox', cost: 500, description: 'Implement robust error handling and retry mechanisms in your integrations.' },
            { id: 'middleware-monitoring', name: 'Integration Monitoring Dashboard', type: 'checkbox', cost: 560, description: 'A dashboard to monitor the health and performance of your integrations.' },
            { id: 'custom-ipaas-connector', name: 'Custom Connector Development for iPaaS', type: 'checkbox', cost: 1100, description: 'Develop a custom connector for an iPaaS platform like Make or Zapier.' },
        ]
    },
    'BI & Analytics': {
        'Dashboarding & Reporting': [
            { id: 'looker-studio-dashboard', name: 'Custom Looker Studio Dashboard', type: 'checkbox', cost: 600, description: 'Create a custom dashboard in Google Looker Studio to visualize your data.' },
            { id: 'power-bi-dashboard', name: 'Custom Power BI Dashboard', type: 'checkbox', cost: 800, description: 'Create a custom dashboard in Microsoft Power BI for in-depth analysis.' },
            { id: 'ga4-setup', name: 'Advanced GA4 Setup & Event Tracking', type: 'checkbox', cost: 500, description: 'Set up and configure Google Analytics 4 with custom event tracking.' },
            { id: 'data-source-integration', name: 'Integration of 3+ Data Sources', type: 'checkbox', cost: 720, description: 'Consolidate data from more than three different sources into one dashboard.' },
            { id: 'automated-pdf-reports', name: 'Automated PDF Report Generation', type: 'checkbox', cost: 520, description: 'Automatically generate and email PDF reports of your dashboards.' },
            { id: 'real-time-kpi-board', name: 'Real-time KPI Monitoring Board', type: 'checkbox', cost: 900, description: 'A live dashboard to monitor your most important Key Performance Indicators.' },
            { id: 'sales-funnel-viz', name: 'Sales Funnel Visualization', type: 'checkbox', cost: 450, description: 'Create a visual representation of your sales funnel to identify drop-offs.' },
            { id: 'customer-segment-viz', name: 'Customer Segmentation Visualization', type: 'checkbox', cost: 560, description: 'Visualize your customer base by different segments and attributes.' },
            { id: 'executive-dashboard', name: 'Executive Summary Dashboard', type: 'checkbox', cost: 650, description: 'A high-level dashboard designed for executive management.' },
            { id: 'dashboard-training', name: 'User Training on Dashboard Usage', type: 'checkbox', cost: 320, description: 'Train your team on how to use and interpret the new dashboards.' },
        ]
    },
    'CRM & Workflow Automation': {
        'Kommo CRM': [
            { id: 'kommo-pipeline-setup', name: 'Advanced Sales Pipeline Setup', type: 'checkbox', cost: 500, description: 'Design and implement a custom, multi-stage sales pipeline in Kommo.' },
            { id: 'kommo-automation', name: 'Automation Rules (Digital Pipeline)', cost: 720, type: 'checkbox', description: 'Set up automation rules to move leads through the pipeline automatically.' },
            { id: 'kommo-integrations', name: 'Integration with WhatsApp & Social Media', cost: 600, type: 'checkbox', description: 'Connect your Kommo account with WhatsApp, Instagram, and other social channels.' },
            { id: 'kommo-webforms', name: 'Custom Webform & Lead Source Setup', cost: 280, type: 'checkbox', description: 'Create and embed webforms on your site to capture leads directly into Kommo.' },
            { id: 'kommo-reporting', name: 'Custom Reporting & Analytics Dashboards', cost: 520, type: 'checkbox', description: 'Build custom reports to track sales performance and team activity.' },
            { id: 'kommo-chatbots', name: 'SalesBot & Chatbot Setup', cost: 650, type: 'checkbox', description: 'Configure chatbots to engage with website visitors and qualify leads.' },
            { id: 'kommo-voip', name: 'VoIP Integration', cost: 360, type: 'checkbox', description: 'Integrate a VoIP phone system to make and receive calls from within Kommo.' },
            { id: 'kommo-team-training', name: 'Team Training & Onboarding', cost: 400, type: 'checkbox', description: 'Train your sales team on how to use Kommo effectively.' },
            { id: 'kommo-data-import', name: 'Data Import from another CRM', cost: 560, type: 'checkbox', description: 'Migrate your existing customer and lead data from another CRM into Kommo.' },
            { id: 'kommo-api', name: 'Custom Integration via Kommo API', cost: 1000, type: 'checkbox', description: 'Develop a custom integration with another system using the Kommo API.' },
        ]
    },
    'AI Bots & Reporting': {
        'Chatbots & AI': [
            { id: 'ai-support-bot', name: 'AI Customer Support Chatbot', cost: 800, type: 'checkbox', description: 'An AI-powered chatbot to answer common customer questions 24/7.' },
            { id: 'ai-lead-qual-bot', name: 'AI Lead Qualification Bot for Website', cost: 900, type: 'checkbox', description: 'A bot that engages website visitors to qualify them as potential leads.' },
            { id: 'internal-kb-bot', name: 'Internal Knowledge Base Bot (Slack/Teams)', cost: 720, type: 'checkbox', description: 'A bot that allows your team to query an internal knowledge base from Slack or Teams.' },
            { id: 'genkit-flow-dev', name: 'Custom Genkit AI Flow Development', cost: 1200, type: 'checkbox', description: 'Develop a custom, multi-step AI workflow using Genkit.' },
            { id: 'gen-ai-content', name: 'Generative AI for Content Creation', cost: 1000, type: 'checkbox', description: 'Use AI to assist in generating blog posts, social media captions, or product descriptions.' },
            { id: 'gen-ai-image', name: 'Generative AI for Image Creation', cost: 1000, type: 'checkbox', description: 'Use AI to generate custom images for your marketing materials or products.' },
            { id: 'sentiment-analysis-setup', name: 'Customer Feedback Sentiment Analysis', cost: 600, type: 'checkbox', description: 'Automatically analyze customer feedback to gauge sentiment.' },
            { id: 'predictive-analytics-reporting', name: 'Predictive Analytics for Sales Forecasting', cost: 1100, type: 'checkbox', description: 'Use historical data to forecast future sales trends.' },
            { id: 'automated-bi-reports', name: 'Automated BI Reporting from AI Insights', cost: 920, type: 'checkbox', description: 'Generate business intelligence reports based on insights derived from AI analysis.' },
            { id: 'voice-ai', name: 'Voice-based AI Assistant Integration', cost: 1400, type: 'checkbox', description: 'Integrate a voice-based AI assistant into your application or website.' },
        ]
    },
    'Business Process Automation': {
        'Workflow Automation': [
            { id: 'monday-com-setup', name: 'Advanced Monday.com Board & Workflow Setup', cost: 600, type: 'checkbox', description: 'Design and implement complex project management boards and automations in Monday.com.' },
            { id: 'cross-dept-workflow', name: 'Cross-Departmental Workflow Automation', cost: 1000, type: 'checkbox', description: 'Automate a process that spans multiple departments, such as sales to finance.' },
            { id: 'document-routing', name: 'Automated Document Approval & Routing', cost: 720, type: 'checkbox', description: 'Create a workflow for automatically routing documents for review and approval.' },
            { id: 'hr-onboarding-automation', name: 'HR Employee Onboarding Automation', cost: 800, type: 'checkbox', description: 'Automate the entire process of onboarding a new employee.' },
            { id: 'finance-approval-automation', name: 'Finance Purchase Order/Invoice Approval', cost: 900, type: 'checkbox', description: 'Automate the approval process for purchase orders or invoices.' },
            { id: 'data-entry-automation', name: 'Automated Data Entry from Emails/Forms', cost: 650, type: 'checkbox', description: 'Automatically extract data from emails or forms and enter it into another system.' },
            { id: 'pmo-dashboard', name: 'Project Management Office (PMO) Dashboard', cost: 1100, type: 'checkbox', description: 'A high-level dashboard to track the status of all projects across the organization.' },
            { id: 'client-onboarding-automation', name: 'Client Onboarding & Project Kickoff Automation', cost: 760, type: 'checkbox', description: 'Automate the process of onboarding a new client and kicking off their project.' },
            { id: 'resource-allocation-automation', name: 'Automated Resource Allocation & Scheduling', cost: 920, type: 'checkbox', description: 'Automatically assign team members to tasks based on availability and skills.' },
            { id: 'process-audit', name: 'Business Process Audit & Optimization Report', cost: 560, type: 'checkbox', description: 'Analyze an existing business process and provide a report on optimization opportunities.' },
        ]
    },
    'SEO & GEO Optimization': {
        'SEO Strategy': [
            { id: 'seo-audit', name: 'Comprehensive SEO Audit', cost: 320, type: 'checkbox', description: 'A deep-dive analysis of your website’s SEO health and opportunities.' },
            { id: 'keyword-research', name: 'In-depth Keyword Research & Strategy (200 keywords)', cost: 400, type: 'checkbox', description: 'Identify and prioritize the top 200 keywords for your business to target.' },
            { id: 'on-page-optimization', name: 'On-Page SEO for up to 20 pages', cost: 600, type: 'checkbox', description: 'Optimize titles, meta tags, headers, and content for up to 20 pages.' },
            { id: 'technical-seo', name: 'Technical SEO Fixes (Site speed, schema)', cost: 720, type: 'checkbox', description: 'Address technical issues like site speed, mobile-friendliness, and structured data.' },
            { id: 'link-building', name: 'Backlink Building Campaign (10 links/month)', cost: 800, type: 'checkbox', description: 'A monthly campaign to acquire high-quality backlinks to your site.' },
            { id: 'local-seo-setup', name: 'Local SEO & Google Business Profile Optimization', cost: 500, type: 'checkbox', description: 'Optimize your online presence to attract local customers.' },
            { id: 'content-strategy-seo', name: 'Content Strategy & Calendar for SEO', cost: 520, type: 'checkbox', description: 'Develop a data-driven content strategy and editorial calendar for SEO success.' },
            { id: 'seo-reporting', name: 'Monthly SEO Performance Reporting & Dashboard', cost: 280, type: 'checkbox', description: 'Receive a monthly report and dashboard to track your SEO performance.' },
            { id: 'voice-search-opt', name: 'Voice Search Optimization', cost: 360, type: 'checkbox', description: 'Optimize your content to appear in voice search results on smart speakers.' },
            { id: 'geo-optimization', name: 'Generative Engine Optimization (GEO) Strategy', cost: 650, type: 'checkbox', description: 'Develop a strategy to optimize for AI-powered search engines like Perplexity.' },
        ]
    },
    'Paid Media & Lead Gen': {
        'Ad Campaign Management': [
            { id: 'meta-ads', name: 'Meta (Facebook/Instagram) Ads Campaign Management', cost: 600, type: 'checkbox', description: 'Manage your ad campaigns on Facebook and Instagram for optimal results.' },
            { id: 'google-ads', name: 'Google Ads (Search, Display, YouTube) Campaign Management', cost: 720, type: 'checkbox', description: 'Manage your Google Ads campaigns across Search, Display, and YouTube.' },
            { id: 'linkedin-ads', name: 'LinkedIn Ads Campaign Management', cost: 650, type: 'checkbox', description: 'Manage your B2B advertising campaigns on LinkedIn.' },
            { id: 'tiktok-ads', name: 'TikTok Ads Campaign Management', cost: 560, type: 'checkbox', description: 'Manage your ad campaigns on TikTok to reach a younger audience.' },
            { id: 'landing-page-design', name: 'High-Conversion Landing Page Design', cost: 500, type: 'checkbox', description: 'Design a landing page optimized to convert visitors into leads.' },
            { id: 'ad-creative-package', name: 'Ad Creative Production (10 images/videos)', cost: 800, type: 'checkbox', description: 'Produce 10 high-quality images or videos for your ad campaigns.' },
            { id: 'ab-testing-ads', name: 'A/B Testing for Ads & Landing Pages', cost: 360, type: 'checkbox', description: 'Run A/B tests to optimize your ad copy, creatives, and landing pages.' },
            { id: 'conversion-tracking-setup', name: 'Advanced Conversion Tracking Setup', cost: 400, type: 'checkbox', description: 'Set up advanced tracking to accurately measure your campaign’s ROI.' },
            { id: 'retargeting-funnel', name: 'Retargeting Funnel Setup', cost: 520, type: 'checkbox', description: 'Set up a multi-stage retargeting funnel to re-engage past visitors.' },
            { id: 'lead-nurturing-automation', name: 'Lead Nurturing Email/SMS Automation', cost: 680, type: 'checkbox', description: 'Create an automated email or SMS sequence to nurture new leads.' },
        ]
    },
    'Social & Content': {
        'Content Production': [
            { id: 'content-strategy-monthly', name: 'Monthly Content Strategy & Calendar', cost: 400, type: 'checkbox', description: 'A monthly plan outlining the content to be created and published.' },
            { id: 'blog-writing', name: 'Blog Writing (4 articles/month)', cost: 500, type: 'checkbox', description: 'Writing and publishing four high-quality blog articles per month.' },
            { id: 'social-media-management', name: 'Social Media Management (2 platforms)', cost: 600, type: 'checkbox', description: 'Ongoing management of two social media platforms, including posting and engagement.' },
            { id: 'short-form-video', name: 'Short-Form Video Production (8 reels/month)', cost: 800, type: 'checkbox', description: 'Production of eight short-form videos (e.g., Reels, TikToks) per month.' },
            { id: 'podcast-production', name: 'Podcast Production (4 episodes/month)', cost: 1000, type: 'checkbox', description: 'End-to-end production for four podcast episodes per month.' },
            { id: 'case-study-writing', name: 'Case Study / Whitepaper Writing', cost: 320, type: 'checkbox', description: 'Writing a detailed case study or whitepaper to showcase your expertise.' },
            { id: 'community-management', name: 'Community Management', cost: 520, type: 'checkbox', description: 'Actively engaging with and growing your online community.' },
            { id: 'influencer-outreach', name: 'Influencer Outreach Campaign', cost: 720, type: 'checkbox', description: 'Identifying and reaching out to relevant influencers for collaborations.' },
            { id: 'email-newsletter', name: 'Weekly Email Newsletter Management', cost: 360, type: 'checkbox', description: 'Managing the creation and sending of a weekly email newsletter.' },
            { id: 'content-distribution', name: 'Content Distribution & Promotion', cost: 280, type: 'checkbox', description: 'Promoting your content across various channels to maximize reach.' },
        ]
    },
    'Growth Workshops': {
        'Team Training': [
            { id: 'growth-hacking-workshop', name: 'Growth Hacking Workshop', cost: 600, type: 'checkbox', description: 'A workshop on unconventional strategies to rapidly grow your business.' },
            { id: 'sales-enablement-workshop', name: 'Sales Enablement Workshop', cost: 600, type: 'checkbox', description: 'Train your sales team with the tools and content they need to succeed.' },
            { id: 'digital-marketing-bootcamp', name: 'Digital Marketing Bootcamp', cost: 1000, type: 'checkbox', description: 'An intensive bootcamp covering all aspects of digital marketing.' },
            { id: 'seo-bootcamp', name: 'SEO Bootcamp', cost: 800, type: 'checkbox', description: 'An in-depth training program on search engine optimization.' },
            { id: 'paid-ads-bootcamp', name: 'Paid Ads Bootcamp', cost: 800, type: 'checkbox', description: 'Learn how to run effective paid advertising campaigns.' },
            { id: 'content-studio-setup', name: 'Content Studio Setup & Training', cost: 1200, type: 'checkbox', description: 'Set up an in-house content studio and train your team to run it.' },
            { id: 'crm-best-practices', name: 'CRM Best Practices Workshop', cost: 500, type: 'checkbox', description: 'Learn how to get the most out of your CRM system.' },
            { id: 'analytics-masterclass', name: 'Analytics & Reporting Masterclass', cost: 720, type: 'checkbox', description: 'A masterclass on using data and analytics to drive decisions.' },
            { id: 'executive-digital-briefing', name: 'Executive Digital Strategy Briefing', cost: 400, type: 'checkbox', description: 'A high-level briefing for executives on digital strategy.' },
            { id: 'custom-workshop', name: 'Custom Workshop Development', cost: 900, type: 'checkbox', description: 'Develop a custom workshop tailored to your team’s specific needs.' },
        ]
    },
    'Helpdesk & SLAs': {
        'Support Plans': [
            { id: 'l1-support', name: 'L1 Technical Support (Email/Ticket)', cost: 400, type: 'checkbox', description: 'Basic front-line support for common issues via email or a ticketing system.' },
            { id: 'l2-support', name: 'L2 Technical Support (Phone/Chat)', cost: 720, type: 'checkbox', description: 'More in-depth technical support for complex issues via phone or chat.' },
            { id: '24-7-support', name: '24/7 Emergency Support Add-on', cost: 1000, type: 'checkbox', description: 'Around-the-clock support for critical, business-impacting emergencies.' },
            { id: 'sla-4hr', name: 'Guaranteed 4-hour Response SLA', cost: 320, type: 'checkbox', description: 'A Service Level Agreement guaranteeing a response to issues within four hours.' },
            { id: 'dedicated-support-portal', name: 'Dedicated Support Portal Setup', cost: 500, type: 'checkbox', description: 'Set up a branded portal for your customers to submit and track support tickets.' },
            { id: 'knowledge-base-creation', name: 'Knowledge Base Creation & Management', cost: 600, type: 'checkbox', description: 'Create and manage a self-service knowledge base for your customers.' },
            { id: 'remote-assistance', name: 'Remote Desktop Assistance', cost: 360, type: 'checkbox', description: 'Provide support by remotely accessing the user’s computer to resolve issues.' },
            { id: 'dedicated-account-manager', name: 'Dedicated Account Manager', cost: 520, type: 'checkbox', description: 'A single point of contact to manage your support needs and escalations.' },
            { id: 'monthly-support-reporting', name: 'Monthly Support Ticket & Performance Reporting', cost: 250, type: 'checkbox', description: 'Receive a monthly report on support ticket volume, resolution times, and performance.' },
            { id: 'on-site-support', name: 'On-site Support (Per Day)', cost: 200, type: 'checkbox', description: 'A technician will come to your location to provide in-person support for a full day.' },
        ]
    },
    'Cybersecurity & Compliance': {
        'Security Services': [
            { id: 'security-audit', name: 'Full Security Audit & Report', cost: 1000, type: 'checkbox', description: 'A comprehensive audit of your application and infrastructure with a detailed report.' },
            { id: 'penetration-testing', name: 'Penetration Testing', cost: 1600, type: 'checkbox', description: 'Simulate a cyber attack to identify and exploit vulnerabilities in your system.' },
            { id: 'vulnerability-scanning', name: 'Continuous Vulnerability Scanning', cost: 500, type: 'checkbox', description: 'Automatically scan your systems for new vulnerabilities on an ongoing basis.' },
            { id: 'waf-cdn-setup', name: 'WAF & CDN Security Setup', cost: 600, type: 'checkbox', description: 'Set up a Web Application Firewall and CDN to protect against common attacks.' },
            { id: 'ddos-mitigation', name: 'DDoS Mitigation Setup', cost: 720, type: 'checkbox', description: 'Implement measures to protect your application from Distributed Denial-of-Service attacks.' },
            { id: 'incident-response-plan', name: 'Security Incident Response Plan Development', cost: 800, type: 'checkbox', description: 'Develop a formal plan for how to respond to a security breach.' },
            { id: 'compliance-audit-gdpr', name: 'GDPR/HIPAA Compliance Audit', cost: 1200, type: 'checkbox', description: 'An audit to assess your compliance with regulations like GDPR or HIPAA.' },
            { id: 'ssl-management', name: 'SSL Certificate Management', cost: 200, type: 'checkbox', description: 'Manage the lifecycle of your SSL certificates to ensure they are always valid.' },
            { id: 'employee-security-training', name: 'Employee Cybersecurity Awareness Training', cost: 600, type: 'checkbox', description: 'Train your employees to recognize and avoid common security threats.' },
            { id: 'security-monitoring-retainer', name: '24/7 Security Monitoring Retainer', cost: 900, type: 'checkbox', description: 'A monthly retainer for continuous monitoring of your security posture.' },
        ]
    },
    'Maintenance & Lifecycle': {
        'Maintenance Plans': [
            { id: 'software-patching', name: 'Monthly Software Patching & Updates', cost: 320, type: 'checkbox', description: 'Apply security patches and updates to your software on a monthly basis.' },
            { id: 'performance-audit-monthly', name: 'Monthly Performance & Optimization Audits', cost: 400, type: 'checkbox', description: 'Conduct a monthly audit to identify and address performance bottlenecks.' },
            { id: 'database-maintenance', name: 'Database Maintenance & Optimization', cost: 500, type: 'checkbox', description: 'Perform routine maintenance on your database to ensure optimal performance.' },
            { id: 'backup-dr-plan', name: 'Backup & Disaster Recovery Plan Setup', cost: 600, type: 'checkbox', description: 'Set up a plan to regularly back up your data and recover from a disaster.' },
            { id: 'automated-backups', name: 'Automated Daily Cloud Backups', cost: 280, type: 'checkbox', description: 'Set up automated daily backups of your data to the cloud.' },
            { id: 'codebase-health-check', name: 'Quarterly Codebase Health Check', cost: 720, type: 'checkbox', description: 'A quarterly review of your codebase to identify and fix potential issues.' },
            { id: 'uptime-monitoring', name: '24/7 Uptime Monitoring & Alerting', cost: 250, type: 'checkbox', description: 'Continuously monitor your application’s uptime and get alerted if it goes down.' },
            { id: 'dependency-update', name: 'Dependency & Framework Update Management', cost: 560, type: 'checkbox', description: 'Manage and update your application’s dependencies and frameworks.' },
            { id: 'staging-env-management', name: 'Staging Environment Management', cost: 450, type: 'checkbox', description: 'Manage a staging environment for testing changes before they go to production.' },
            { id: 'load-testing', name: 'Annual Load Testing', cost: 800, type: 'checkbox', description: 'Conduct an annual load test to ensure your application can handle traffic spikes.' },
        ]
    },
    'Onboarding & Handover': {
        'Enablement Packages': [
            { id: 'sop-documentation', name: 'Standard Operating Procedures (SOP) Documentation', cost: 600, type: 'checkbox', description: 'Create detailed documentation for your standard operating procedures.' },
            { id: 'user-training-sessions', name: 'Comprehensive User Training Sessions (3 sessions)', cost: 500, type: 'checkbox', description: 'Three comprehensive training sessions for your end-users.' },
            { id: 'admin-training-sessions', name: 'Administrator Training Sessions', cost: 400, type: 'checkbox', description: 'Specialized training for system administrators.' },
            { id: 'video-tutorials', name: 'Creation of Video Tutorials', cost: 720, type: 'checkbox', description: 'Create a library of video tutorials to help users learn the system.' },
            { id: 'knowledge-base-setup', name: 'Internal Knowledge Base Setup', cost: 650, type: 'checkbox', description: 'Set up an internal knowledge base for your team to reference.' },
            { id: 'system-architecture-docs', name: 'System Architecture & Code Documentation', cost: 800, type: 'checkbox', description: 'Detailed documentation of the system’s architecture and codebase.' },
            { id: 'post-launch-support', name: '30-Day Post-Launch Hypercare Support', cost: 520, type: 'checkbox', description: 'Intensive support for the first 30 days after launch to ensure a smooth transition.' },
            { id: 'train-the-trainer', name: 'Train-the-Trainer Program', cost: 900, type: 'checkbox', description: 'A program to train your internal staff to become trainers themselves.' },
            { id: 'handover-checklist', name: 'Detailed Handover Checklist & Process', cost: 320, type: 'checkbox', description: 'A detailed checklist to ensure a smooth and complete handover.' },
            { id: 'credential-management-plan', name: 'Credential & Access Management Handover Plan', cost: 280, type: 'checkbox', description: 'A secure plan for handing over all necessary credentials and access.' },
        ]
    },
    'Product Training': {
        'Software Training': [
            { id: 'kommo-user-training', name: 'Kommo CRM User Training', cost: 320, type: 'checkbox', description: 'Training for end-users on how to use Kommo CRM effectively.' },
            { id: 'monday-pm-training', name: 'Monday.com Project Management Training', cost: 360, type: 'checkbox', description: 'Training on how to use Monday.com for project management.' },
            { id: 'erp-pos-training', name: 'ERP/POS User Training', cost: 500, type: 'checkbox', description: 'Training for users on your specific ERP or Point-of-Sale system.' },
            { id: 'cms-training-wordpress', name: 'WordPress Content Management Training', cost: 280, type: 'checkbox', description: 'Learn how to manage content on a WordPress website.' },
            { id: 'cms-training-shopify', name: 'Shopify Store Management Training', cost: 400, type: 'checkbox', description: 'Learn how to manage products, orders, and customers in Shopify.' },
            { id: 'ga4-training', name: 'Google Analytics 4 for Beginners', cost: 450, type: 'checkbox', description: 'An introductory course on how to use Google Analytics 4.' },
            { id: 'custom-app-training', name: 'Training on Custom-Built Application', cost: 600, type: 'checkbox', description: 'Customized training for an application that was built specifically for you.' },
            { id: 'admin-training-software', name: 'System Administrator Training', cost: 720, type: 'checkbox', description: 'Advanced training for administrators on how to manage the system.' },
            { id: 'user-adoption-program', name: 'User Adoption Program & Materials', cost: 800, type: 'checkbox', description: 'A program designed to encourage users to adopt a new system.' },
            { id: 'refresher-training', name: 'Quarterly Refresher Training Sessions', cost: 560, type: 'checkbox', description: 'Quarterly training sessions to refresh your team’s knowledge.' },
        ]
    },
    'Marketing Bootcamps': {
        'Digital Marketing': [
            { id: 'bootcamp-meta-google-ads', name: 'Meta & Google Ads Bootcamp', cost: 1000, type: 'checkbox', description: 'An intensive bootcamp on running effective ad campaigns on Meta and Google.' },
            { id: 'bootcamp-advanced-seo', name: 'Advanced SEO & Content Strategy Bootcamp', cost: 900, type: 'checkbox', description: 'A bootcamp on advanced SEO techniques and content strategy.' },
            { id: 'bootcamp-influencer-marketing', name: 'Influencer Marketing & Studio Creation Bootcamp', cost: 800, type: 'checkbox', description: 'Learn how to run influencer marketing campaigns and create your own content studio.' },
            { id: 'bootcamp-email-marketing', name: 'Email Marketing Automation Bootcamp', cost: 720, type: 'checkbox', description: 'A bootcamp on setting up and running automated email marketing campaigns.' },
            { id: 'bootcamp-cro', name: 'Conversion Rate Optimization (CRO) Bootcamp', cost: 920, type: 'checkbox', description: 'Learn how to optimize your website to convert more visitors.' },
            { id: 'bootcamp-social-media', name: 'Social Media Management Bootcamp', cost: 760, type: 'checkbox', description: 'A bootcamp on effective social media management and community building.' },
            { id: 'bootcamp-analytics', name: 'Marketing Analytics & Reporting Bootcamp', cost: 840, type: 'checkbox', description: 'Learn how to use analytics to measure and improve your marketing performance.' },
            { id: 'bootcamp-content-marketing', name: 'Content Marketing & Strategy Bootcamp', cost: 960, type: 'checkbox', description: 'A bootcamp on creating and executing a successful content marketing strategy.' },
            { id: 'bootcamp-growth-hacking', name: 'Growth Hacking for Marketers Bootcamp', cost: 1040, type: 'checkbox', description: 'Learn unconventional strategies to rapidly grow your business.' },
            { id: 'bootcamp-custom', name: 'Custom Marketing Bootcamp for your Team', cost: 1400, type: 'checkbox', description: 'Develop a custom marketing bootcamp tailored to your team’s specific needs.' },
        ]
    },
    'Design & Tech': {
        'Workshops': [
            { id: 'workshop-ui-ux-fundamentals', name: 'UI/UX Fundamentals Workshop (Figma)', cost: 600, type: 'checkbox', description: 'A workshop covering the fundamentals of UI/UX design using Figma.' },
            { id: 'workshop-canva-marketing', name: 'Canva for Marketing Teams Workshop', cost: 400, type: 'checkbox', description: 'Learn how to use Canva to create professional marketing materials.' },
            { id: 'workshop-motion-design-basics', name: 'Motion Design Basics Workshop (After Effects)', cost: 720, type: 'checkbox', description: 'An introductory workshop on motion design using Adobe After Effects.' },
            { id: 'workshop-design-thinking', name: 'Design Thinking Workshop', cost: 650, type: 'checkbox', description: 'A workshop on the design thinking process for problem-solving.' },
            { id: 'workshop-html-css', name: 'Introduction to HTML/CSS', cost: 500, type: 'checkbox', description: 'A beginner’s workshop on the building blocks of the web.' },
            { id: 'workshop-javascript', name: 'JavaScript for Beginners', cost: 560, type: 'checkbox', description: 'An introductory workshop on the JavaScript programming language.' },
            { id: 'workshop-react-nextjs', name: 'Introduction to React & Next.js', cost: 800, type: 'checkbox', description: 'A beginner’s workshop on building web applications with React and Next.js.' },
            { id: 'workshop-gen-ai', name: 'Introduction to Generative AI & Genkit', cost: 900, type: 'checkbox', description: 'An introduction to the world of generative AI and how to use Genkit.' },
            { id: 'workshop-prompt-engineering', name: 'Prompt Engineering Basics Workshop', cost: 680, type: 'checkbox', description: 'Learn the basics of how to write effective prompts for AI models.' },
            { id: 'workshop-api-basics', name: 'Understanding APIs for Non-Developers', cost: 520, type: 'checkbox', description: 'A workshop that explains what APIs are and how they work, for a non-technical audience.' },
        ]
    },
    'E-commerce Skills': {
        'E-commerce Training': [
            { id: 'training-shopify-management', name: 'Shopify Store Management & Operations Training', cost: 600, type: 'checkbox', description: 'Learn how to manage your Shopify store, from products to orders.' },
            { id: 'training-ecommerce-seo', name: 'Product SEO & CRO for E-commerce Training', cost: 720, type: 'checkbox', description: 'Learn how to optimize your product pages for search and conversions.' },
            { id: 'training-marketplace-compliance', name: 'Marketplace Compliance (Amazon, eBay) Training', cost: 650, type: 'checkbox', description: 'Learn the rules and regulations for selling on major marketplaces.' },
            { id: 'training-inventory-management', name: 'Inventory Management Best Practices Training', cost: 520, type: 'checkbox', description: 'Learn best practices for managing your e-commerce inventory.' },
            { id: 'training-ecommerce-ads', name: 'Paid Advertising for E-commerce Stores Training', cost: 800, type: 'checkbox', description: 'Learn how to run effective paid ad campaigns for your online store.' },
            { id: 'training-social-commerce', name: 'Social Commerce Strategies Training', cost: 680, type: 'checkbox', description: 'Learn how to sell your products directly on social media platforms.' },
            { id: 'training-ecommerce-analytics', name: 'E-commerce Analytics & Reporting Training', cost: 760, type: 'checkbox', description: 'Learn how to use analytics to understand and grow your e-commerce business.' },
            { id: 'training-customer-experience', name: 'Optimizing the E-commerce Customer Experience', cost: 560, type: 'checkbox', description: 'Learn how to create a great customer experience for your online store.' },
            { id: 'training-personalization', name: 'E-commerce Personalization Strategies Training', cost: 900, type: 'checkbox', description: 'Learn how to personalize the shopping experience for your customers.' },
            { id: 'training-headless-commerce', name: 'Introduction to Headless Commerce', cost: 1000, type: 'checkbox', description: 'An introductory training on the concepts and benefits of headless commerce.' },
        ]
    },
    'Marketplace Management': {
        'Account Management': [
            { id: 'marketplace-account-setup', name: 'Marketplace Account Setup (Amazon, eBay, etc.)', cost: 300, type: 'checkbox', description: 'Initial setup and verification for your seller account on a major marketplace.' },
            { id: 'product-listing-optimization', name: 'Product Listing & SEO (up to 20 products)', cost: 500, type: 'checkbox', description: 'Create and optimize up to 20 product listings with titles, descriptions, and keywords.' },
            { id: 'inventory-management-marketplace', name: 'Inventory & Stock Management', cost: 250, type: 'checkbox', description: 'Monitor stock levels, set alerts, and manage inventory across marketplaces.' },
            { id: 'order-processing-fulfillment', name: 'Order Processing & Fulfillment Coordination', cost: 350, type: 'checkbox', description: 'Manage incoming orders, coordinate with fulfillment centers (like FBA), and handle tracking.' },
            { id: 'customer-service-marketplace', name: 'Customer Service & Communication', cost: 400, type: 'checkbox', description: 'Handle customer inquiries, feedback, and pre/post-sale support on the marketplace.' },
            { id: 'review-reputation-management', name: 'Review & Reputation Management', cost: 300, type: 'checkbox', description: 'Proactively manage product reviews and seller feedback to maintain a positive reputation.' },
            { id: 'marketplace-advertising', name: 'Marketplace PPC Campaign Management', cost: 450, type: 'checkbox', description: 'Manage Pay-Per-Click advertising campaigns (e.g., Amazon Sponsored Products) to boost visibility.' },
            { id: 'performance-analytics-reporting', name: 'Performance Analytics & Reporting', cost: 200, type: 'checkbox', description: 'Provide monthly reports on sales, traffic, conversion rates, and account health.' },
            { id: 'a-plus-content', name: 'A+ Content / Enhanced Brand Content Creation', cost: 400, type: 'checkbox', description: 'Design and develop A+ Content for Amazon or enhanced content for other marketplaces.' },
            { id: 'case-log-management', name: 'Case Log & Issue Resolution with Marketplace Support', cost: 250, type: 'checkbox', description: 'Manage and resolve issues by communicating with marketplace support teams.' },
        ],
    },
    'Virtual Assistant Services': {
        'Administrative Support': [
            { id: 'email-management', name: 'Email Management & Filtering', cost: 150, type: 'checkbox', description: 'Organize, filter, and respond to emails to keep your inbox clean.' },
            { id: 'calendar-management', name: 'Calendar Management & Scheduling', cost: 150, type: 'checkbox', description: 'Schedule appointments, manage your calendar, and send reminders.' },
            { id: 'data-entry', name: 'Data Entry & Spreadsheet Management', cost: 200, type: 'checkbox', description: 'Perform data entry tasks and manage spreadsheets with accuracy.' },
            { id: 'document-preparation', name: 'Document Preparation & Formatting', cost: 180, type: 'checkbox', description: 'Create, format, and proofread documents, presentations, and reports.' },
            { id: 'online-research', name: 'Online Research', cost: 220, type: 'checkbox', description: 'Conduct research on various topics and compile information as requested.' },
            { id: 'travel-booking', name: 'Travel Arrangements & Booking', cost: 120, type: 'checkbox', description: 'Handle flight, hotel, and transport bookings for your business travel.' },
            { id: 'crm-data-management', name: 'CRM Data Management', cost: 250, type: 'checkbox', description: 'Update and maintain customer information in your CRM system.' },
            { id: 'social-media-scheduling', name: 'Basic Social Media Scheduling', cost: 180, type: 'checkbox', description: 'Schedule social media posts across your platforms using a content calendar.' },
            { id: 'customer-support-initial', name: 'Initial Customer Support (Tier 1)', cost: 300, type: 'checkbox', description: 'Provide first-level customer support via email or chat.' },
            { id: 'transcription-services', name: 'Transcription Services', cost: 160, type: 'checkbox', description: 'Transcribe audio or video recordings into text documents.' },
        ],
    },
};
